use_frameworks!

target 'componentDyyTest_Example' do
  pod 'componentDyyTest', :path => '../'

  target 'componentDyyTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
